<a href="https://colab.research.google.com/github/ggorovod/Fintech_Bootcamp_Challenge_13/blob/main/GC_venture_funding_with_deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [ ]:
# Imports
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [ ]:
# Upload credit_card_transactions.csv to Colab
from google.colab import files

csv_file = files.upload()

Saving applicants_data.csv to applicants_data.csv

In [ ]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df = pd.read_csv('applicants_data.csv')

# Review the DataFrame
applicant_data_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Review the data types associated with the columns
applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [ ]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(columns=['EIN', "NAME"])

# Review the DataFrame
applicant_data_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [ ]:
# Create a list of categorical variables 
categorical_variables = list(applicant_data_df.dtypes[applicant_data_df.dtypes == 'object'].index)

# Display the categorical variables list
categorical_variables

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [ ]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

In [ ]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables])

In [ ]:
# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(
    encoded_data, columns = enc.get_feature_names(categorical_variables))


# Review the DataFrame
encoded_df.head()

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [ ]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
encoded_df = pd.concat([encoded_df, applicant_data_df[list(applicant_data_df.dtypes[applicant_data_df.dtypes == 'int64'].index)]], axis=1)

# Review the Dataframe
encoded_df.head()

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y,STATUS,ASK_AMT,IS_SUCCESSFUL
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,1
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,108590,1
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,6692,1
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,142590,1

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [ ]:
# Define the target set y using the IS_SUCCESSFUL column
y = encoded_df['IS_SUCCESSFUL']

# Display a sample of y
y

0        1
1        1
2        0
3        1
4        1
        ..
34294    0
34295    0
34296    0
34297    1
34298    0
Name: IS_SUCCESSFUL, Length: 34299, dtype: int64

In [ ]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = encoded_df.drop(columns = 'IS_SUCCESSFUL')
# Review the features DataFrame
X

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y,STATUS,ASK_AMT
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,108590
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,6692
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,142590
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
34295,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
34296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
34297,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
34298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1,36500179

### Step 6: Split the features and target sets into training and testing datasets.

In [ ]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [ ]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [ ]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [ ]:
# Define the number of neurons in the output layer
number_output_neurons = 1

number_output_neurons

1

In [ ]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 = (number_input_features +1) // 2

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

58

In [ ]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 =  (hidden_nodes_layer1 +1) // 2

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

29

In [ ]:
# Create the Sequential model instance
nn = Sequential()

In [ ]:
# Add the first hidden layer
nn.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation='relu'))

In [ ]:
# Add the second hidden layer
nn.add(Dense(units=hidden_nodes_layer2, activation='relu'))

In [ ]:
# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(units=number_output_neurons, activation='sigmoid'))

In [ ]:
# Display the Sequential model summary
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 58)                6786

 dense_1 (Dense)             (None, 29)                1711

 dense_2 (Dense)             (None, 1)                 30

=================================================================
Total params: 8,527
Trainable params: 8,527
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [ ]:
# Compile the Sequential model
nn.compile(loss = 'binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
# Fit the model using 50 epochs and the training data
nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5783 - accuracy: 0.7206
Epoch 2/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5546 - accuracy: 0.7296
Epoch 3/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5512 - accuracy: 0.7290
Epoch 4/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5482 - accuracy: 0.7322
Epoch 5/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5470 - accuracy: 0.7331
Epoch 6/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5451 - accuracy: 0.7327
Epoch 7/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5451 - accuracy: 0.7331
Epoch 8/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5447 - accuracy: 0.7338
Epoch 9/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5436 - accuracy: 0.7336
Epoch 10/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5427 - accuracy: 0.7347
Epoch 11/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7356
Epoch 12/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5423 - accuracy: 0.7350
Epoch 13/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5415 - accuracy: 0.7350
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5413 - accuracy: 0.7353
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7352
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7363
Epoch 17/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5393 - accuracy: 0.7358
Epoch 18/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5393 - accuracy: 0.7361
Epoch 19/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7346
Epoch 20/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7378
Epoch 21/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7364
Epoch 22/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5379 - accuracy: 0.7371
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5379 - accuracy: 0.7387
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5378 - accuracy: 0.7375
Epoch 25/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5369 - accuracy: 0.7376
Epoch 26/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7376
Epoch 27/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5369 - accuracy: 0.7392
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7383
Epoch 29/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7395
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5359 - accuracy: 0.7388
Epoch 31/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7386
Epoch 32/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5358 - accuracy: 0.7392
Epoch 33/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5358 - accuracy: 0.7385
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5352 - accuracy: 0.7391
Epoch 35/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5352 - accuracy: 0.7392
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5352 - accuracy: 0.7387
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5348 - accuracy: 0.7399
Epoch 38/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5342 - accuracy: 0.7397
Epoch 39/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5343 - accuracy: 0.7392
Epoch 40/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5339 - accuracy: 0.7400
Epoch 41/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5345 - accuracy: 0.7399
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5339 - accuracy: 0.7400
Epoch 43/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5339 - accuracy: 0.7394
Epoch 44/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7392
Epoch 45/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5335 - accuracy: 0.7405
Epoch 46/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5333 - accuracy: 0.7397
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5327 - accuracy: 0.7402
Epoch 48/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5328 - accuracy: 0.7398
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5326 - accuracy: 0.7407
Epoch 50/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5326 - accuracy: 0.7407

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [ ]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5573 - accuracy: 0.7318 - 515ms/epoch - 2ms/step
Loss: 0.5572970509529114, Accuracy: 0.7317784428596497

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [ ]:
# Set the model's file path
file_path = ('Resources/AlphabetSoup.h5')

# Export your model to a HDF5 file
nn.save(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [ ]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [ ]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 1

In [ ]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = (2/3) * (number_input_features + 1)

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

78.0

In [ ]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [ ]:
# First hidden layer
nn_A1.add(Dense(units=hidden_nodes_layer1_A1, input_dim=number_input_features, activation='relu'))


# Output layer
nn_A1.add(Dense(units=number_output_neurons_A1, activation="sigmoid"))


# Check the structure of the model
nn_A1.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_6 (Dense)             (None, 78)                9126

 dense_7 (Dense)             (None, 1)                 79

=================================================================
Total params: 9,205
Trainable params: 9,205
Non-trainable params: 0
_________________________________________________________________

In [ ]:
# Compile the Sequential model
nn_A1.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'] )

In [ ]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5760 - accuracy: 0.7210
Epoch 2/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5568 - accuracy: 0.7280
Epoch 3/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5526 - accuracy: 0.7302
Epoch 4/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5518 - accuracy: 0.7306
Epoch 5/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5508 - accuracy: 0.7303
Epoch 6/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5494 - accuracy: 0.7308
Epoch 7/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5480 - accuracy: 0.7329
Epoch 8/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5482 - accuracy: 0.7335
Epoch 9/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5464 - accuracy: 0.7322
Epoch 10/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5460 - accuracy: 0.7328
Epoch 11/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5460 - accuracy: 0.7334
Epoch 12/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5452 - accuracy: 0.7331
Epoch 13/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5444 - accuracy: 0.7333
Epoch 14/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5436 - accuracy: 0.7352
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5436 - accuracy: 0.7334
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5434 - accuracy: 0.7345
Epoch 17/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5427 - accuracy: 0.7345
Epoch 18/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5436 - accuracy: 0.7342
Epoch 19/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5427 - accuracy: 0.7345
Epoch 20/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5420 - accuracy: 0.7341
Epoch 21/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5418 - accuracy: 0.7338
Epoch 22/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5417 - accuracy: 0.7347
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5413 - accuracy: 0.7351
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5413 - accuracy: 0.7354
Epoch 25/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7345
Epoch 26/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7357
Epoch 27/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7364
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7360
Epoch 29/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5403 - accuracy: 0.7360
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7356
Epoch 31/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7366
Epoch 32/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5399 - accuracy: 0.7355
Epoch 33/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5396 - accuracy: 0.7357
Epoch 34/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5395 - accuracy: 0.7369
Epoch 35/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5392 - accuracy: 0.7365
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7362
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5388 - accuracy: 0.7368
Epoch 38/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5392 - accuracy: 0.7358
Epoch 39/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7362
Epoch 40/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5383 - accuracy: 0.7370
Epoch 41/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7371
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7366
Epoch 43/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5386 - accuracy: 0.7359
Epoch 44/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5381 - accuracy: 0.7369
Epoch 45/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5386 - accuracy: 0.7362
Epoch 46/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5380 - accuracy: 0.7370
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5380 - accuracy: 0.7369
Epoch 48/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5383 - accuracy: 0.7379
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5377 - accuracy: 0.7376
Epoch 50/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5376 - accuracy: 0.7379

#### Alternative Model 2

In [ ]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [ ]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 1

In [ ]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = ((number_input_features + number_output_neurons_A2) // 2) - 1

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

57

In [ ]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [ ]:
# First hidden layer
nn_A2.add(Dense(units=hidden_nodes_layer1_A2, input_dim=number_input_features, activation='relu'))


# Output layer
nn_A2.add(Dense(units=number_output_neurons_A2, activation='sigmoid'))

# Check the structure of the model
nn_A2.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_8 (Dense)             (None, 57)                6669

 dense_9 (Dense)             (None, 1)                 58

=================================================================
Total params: 6,727
Trainable params: 6,727
Non-trainable params: 0
_________________________________________________________________

In [ ]:
# Compile the model
nn_A2.compile(loss= 'binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
# Fit the model
nn_A2.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5914 - accuracy: 0.7161
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5580 - accuracy: 0.7295
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5531 - accuracy: 0.7296
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5511 - accuracy: 0.7308
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5499 - accuracy: 0.7309
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5487 - accuracy: 0.7311
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5486 - accuracy: 0.7311
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5471 - accuracy: 0.7333
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5469 - accuracy: 0.7320
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5467 - accuracy: 0.7325
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5461 - accuracy: 0.7329
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5456 - accuracy: 0.7327
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5448 - accuracy: 0.7321
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5448 - accuracy: 0.7324
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5441 - accuracy: 0.7330
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5437 - accuracy: 0.7335
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5432 - accuracy: 0.7333
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5439 - accuracy: 0.7344
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5428 - accuracy: 0.7343
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5427 - accuracy: 0.7328
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5424 - accuracy: 0.7350
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5423 - accuracy: 0.7352
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5421 - accuracy: 0.7343
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7339
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5417 - accuracy: 0.7341
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5414 - accuracy: 0.7343
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5414 - accuracy: 0.7341
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5415 - accuracy: 0.7352
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7347
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7365
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7351
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5403 - accuracy: 0.7363
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7350
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7365
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5403 - accuracy: 0.7343
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5400 - accuracy: 0.7357
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5399 - accuracy: 0.7348
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7364
Epoch 39/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5397 - accuracy: 0.7369
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5393 - accuracy: 0.7357
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5396 - accuracy: 0.7362
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7358
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5396 - accuracy: 0.7360
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5386 - accuracy: 0.7360
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5392 - accuracy: 0.7353
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7369
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5391 - accuracy: 0.7367
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5386 - accuracy: 0.7361
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5381 - accuracy: 0.7382
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7372
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5383 - accuracy: 0.7364
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7364
Epoch 53/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5381 - accuracy: 0.7382
Epoch 54/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5383 - accuracy: 0.7361
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5378 - accuracy: 0.7363
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5376 - accuracy: 0.7370
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5379 - accuracy: 0.7364
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5376 - accuracy: 0.7369
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7372
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5375 - accuracy: 0.7370
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7376
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7380
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5367 - accuracy: 0.7374
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5368 - accuracy: 0.7376
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5373 - accuracy: 0.7367
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5364 - accuracy: 0.7371
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7374
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7375
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5370 - accuracy: 0.7367
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5361 - accuracy: 0.7384
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5363 - accuracy: 0.7370
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5368 - accuracy: 0.7381
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7379
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5360 - accuracy: 0.7379
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5358 - accuracy: 0.7382
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5355 - accuracy: 0.7382
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5360 - accuracy: 0.7389
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5361 - accuracy: 0.7379
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7375
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5360 - accuracy: 0.7388
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5358 - accuracy: 0.7382
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5359 - accuracy: 0.7378
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7392
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5355 - accuracy: 0.7393
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7388
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5355 - accuracy: 0.7393
Epoch 87/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5363 - accuracy: 0.7385
Epoch 88/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5352 - accuracy: 0.7394
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5348 - accuracy: 0.7399
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5351 - accuracy: 0.7369
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5347 - accuracy: 0.7392
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5348 - accuracy: 0.7388
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7394
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5351 - accuracy: 0.7385
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5346 - accuracy: 0.7397
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5348 - accuracy: 0.7402
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5346 - accuracy: 0.7400
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5344 - accuracy: 0.7385
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5349 - accuracy: 0.7390
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5342 - accuracy: 0.7400

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [ ]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
268/268 - 1s - loss: 0.7011 - accuracy: 0.5652 - 537ms/epoch - 2ms/step
Loss: 0.7010924816131592, Accuracy: 0.5652478337287903

In [ ]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy =nn_A1.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
268/268 - 1s - loss: 0.5619 - accuracy: 0.7313 - 715ms/epoch - 3ms/step
Loss: 0.5619431734085083, Accuracy: 0.7313119769096375

In [ ]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
268/268 - 0s - loss: 0.5660 - accuracy: 0.7269 - 443ms/epoch - 2ms/step
Loss: 0.565991222858429, Accuracy: 0.7268804907798767

### Step 3: Save each of your alternative models as an HDF5 file.

In [ ]:
# Set the file path for the first alternative model
file_path = ('Resources/AlphabetSoup_A1.h5')


# Export your model to a HDF5 file
nn_A1.save(file_path)

In [ ]:
# Set the file path for the second alternative model
file_path = ('Resources/AlphabetSoup_A2.h5')

# Export your model to a HDF5 file
nn_A2.save(file_path)